name: CI

on:
  push:
    branches: [ "hw1" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest
    container: leshiy1295/gcc_linters_valgrind_cmake_gtest

    steps:
    - uses: actions/checkout@v3

    - name: build
      run: cmake ./hw1 -B ./hw1/build

    - name: make & run
      # Build your program with the given configuration
      working-directory: ./hw1/build
      run: |
        make
        ./solution

    - name: test
      working-directory: ./hw1/build/tests
      run: ./test_solution

    - name: test coverage 
      working-directory: ./hw1/build
      run: |
        apt install lcov -y
        lcov -t "tests/test_solution" -o coverage.info -c -d src
        genhtml -o report coverage.info

    - name: valgrind test
      working-directory: ./hw1/build/tests
      run: |
        export ASAN_OPTIONS=verify_asan_link_order=0
        valgrind --tool=memcheck --leak-check=yes ./test_solution

